import React, { useState } from "react";
import { motion } from "framer-motion";
import { 
  Filter, 
  Columns, 
  Edit3, 
  Sparkles, 
  Binary, 
  Layers, 
  ArrowUpDown, 
  CopyX, 
  Calculator, 
  BarChart2,
  Code2,
  Check
} from "lucide-react";

interface OperationItem {
  type: string;
  name: string;
  category: "Transform" | "Clean" | "Aggregate" | "Output";
  icon: React.ElementType;
  description: string;
  sampleDsl: string;
  pandasCode: string;
}

const OPERATIONS: OperationItem[] = [
  {
    type: "filter",
    name: "filter",
    category: "Transform",
    icon: Filter,
    description: "Filter dataset rows by logical expressions (==, !=, >, <, in, contains).",
    sampleDsl: `{"type": "filter", "params": {"column": "status", "op": "==", "value": "active"}}`,
    pandasCode: `df[df['status'] == 'active']`
  },
  {
    type: "select_columns",
    name: "select_columns",
    category: "Transform",
    icon: Columns,
    description: "Keep specific subset of columns and drop unneeded data fields.",
    sampleDsl: `{"type": "select_columns", "params": {"columns": ["user_id", "revenue", "created_at"]}}`,
    pandasCode: `df[['user_id', 'revenue', 'created_at']]`
  },
  {
    type: "rename",
    name: "rename",
    category: "Clean",
    icon: Edit3,
    description: "Rename column headers to match required schema conventions.",
    sampleDsl: `{"type": "rename", "params": {"columns": {"orig_col": "new_column_name"}}}`,
    pandasCode: `df.rename(columns={'orig_col': 'new_column_name'})`
  },
  {
    type: "fill_na",
    name: "fill_na",
    category: "Clean",
    icon: Sparkles,
    description: "Handle missing values with scalar fallbacks, mean, median, or forward fill.",
    sampleDsl: `{"type": "fill_na", "params": {"column": "revenue", "value": 0}}`,
    pandasCode: `df['revenue'].fillna(0)`
  },
  {
    type: "cast_type",
    name: "cast_type",
    category: "Clean",
    icon: Binary,
    description: "Convert string dates to datetime64, numbers to float/int, or booleans.",
    sampleDsl: `{"type": "cast_type", "params": {"column": "timestamp", "target_type": "datetime"}}`,
    pandasCode: `pd.to_datetime(df['timestamp'])`
  },
  {
    type: "groupby_agg",
    name: "groupby_agg",
    category: "Aggregate",
    icon: Layers,
    description: "Group data by key dimensions and aggregate metrics (sum, mean, count, min, max).",
    sampleDsl: `{"type": "groupby_agg", "params": {"by": ["region"], "aggs": {"sales": "sum"}}}`,
    pandasCode: `df.groupby(['region'])['sales'].sum().reset_index()`
  },
  {
    type: "sort",
    name: "sort",
    category: "Transform",
    icon: ArrowUpDown,
    description: "Sort rows by one or more columns in ascending or descending order.",
    sampleDsl: `{"type": "sort", "params": {"by": ["sales"], "ascending": false}}`,
    pandasCode: `df.sort_values(by=['sales'], ascending=False)`
  },
  {
    type: "deduplicate",
    name: "deduplicate",
    category: "Clean",
    icon: CopyX,
    description: "Remove duplicate records based on unique key columns or full row matches.",
    sampleDsl: `{"type": "deduplicate", "params": {"subset": ["user_id"], "keep": "first"}}`,
    pandasCode: `df.drop_duplicates(subset=['user_id'], keep='first')`
  },
  {
    type: "compute_column",
    name: "compute_column",
    category: "Transform",
    icon: Calculator,
    description: "Create calculated columns using secure pandas evaluation expressions.",
    sampleDsl: `{"type": "compute_column", "params": {"new_column": "total", "expr": "price * qty"}}`,
    pandasCode: `df.eval('total = price * qty')`
  },
  {
    type: "visualize",
    name: "visualize",
    category: "Output",
    icon: BarChart2,
    description: "Generate interactive Plotly bar, line, scatter, pie, histogram, or heatmap charts.",
    sampleDsl: `{"type": "visualize", "params": {"chart_type": "bar", "x": "region", "y": "sales"}}`,
    pandasCode: `px.bar(df, x='region', y='sales')`
  }
];

export default function OperationsGrid() {
  const [selectedOpType, setSelectedOpType] = useState<string>("groupby_agg");
  const activeOp = OPERATIONS.find((op) => op.type === selectedOpType) || OPERATIONS[5];

  return (
    <section className="w-full my-20">
      <div className="flex flex-col md:flex-row items-start md:items-end justify-between mb-8">
        <div>
          <span className="font-mono text-xs text-[#4DD9C4] uppercase tracking-widest font-semibold">
            PIPELINE ENGINE SPECIFICATION
          </span>
          <h2 className="font-display text-3xl font-bold text-[#E7E9EE] mt-2 tracking-tight">
            10 Deterministic Operations
          </h2>
          <p className="text-[#8B92A3] text-sm mt-1 max-w-xl font-sans">
            Every step generated by Glasswork resolves strictly to one of 10 whitelist operations — no black boxes, no unverified code execution.
          </p>
        </div>
        <div className="font-mono text-xs text-[#8B92A3] mt-4 md:mt-0 flex items-center gap-2 px-3 py-1.5 bg-[#12161F] rounded border border-white/10">
          <Code2 className="w-3.5 h-3.5 text-[#F5A623]" />
          <span>Pandas 2.2 + Plotly Backend</span>
        </div>
      </div>

      {/* 10 Operations Node-Chips Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3 mb-6">
        {OPERATIONS.map((op, idx) => {
          const IconComp = op.icon;
          const isSelected = selectedOpType === op.type;

          return (
            <motion.button
              key={op.type}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.2, delay: idx * 0.03 }}
              onClick={() => setSelectedOpType(op.type)}
              className={`p-3.5 rounded-lg border text-left font-mono transition-all duration-150 relative group ${
                isSelected
                  ? "bg-[#12161F] border-[#F5A623] text-[#E7E9EE] ring-1 ring-[#F5A623]/30 shadow-[0_0_15px_rgba(245,166,35,0.2)]"
                  : "bg-[#12161F]/70 border-cyan-500/20 text-[#8B92A3] hover:border-[#4DD9C4] hover:text-[#E7E9EE] hover:bg-[#12161F]"
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <div className={`p-1.5 rounded ${isSelected ? "bg-[#F5A623]/20 text-[#F5A623]" : "bg-[#4DD9C4]/10 text-[#4DD9C4]"}`}>
                  <IconComp className="w-4 h-4" />
                </div>
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-white/5 text-[#8B92A3]">
                  {op.category}
                </span>
              </div>
              <p className="text-xs font-semibold text-[#E7E9EE] truncate">
                {op.name}
              </p>
            </motion.button>
          );
        })}
      </div>

      {/* Selected Operation Parameter & Code Preview Card */}
      <motion.div 
        key={activeOp.type}
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.2 }}
        className="p-5 rounded-xl bg-[#0B0E14] border border-cyan-500/25 grid grid-cols-1 md:grid-cols-2 gap-6"
      >
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="font-mono text-xs px-2.5 py-1 rounded bg-[#F5A623]/15 text-[#F5A623] border border-[#F5A623]/30 font-bold">
              {activeOp.name}
            </span>
            <span className="font-mono text-xs text-[#8B92A3]">[{activeOp.category} Node]</span>
          </div>
          <p className="text-sm text-[#E7E9EE] font-sans mt-2 leading-relaxed">
            {activeOp.description}
          </p>

          <div className="mt-4 space-y-2">
            <span className="font-mono text-xs text-[#8B92A3] block">Engine Security:</span>
            <div className="flex items-center gap-2 text-xs font-mono text-[#4DD9C4]">
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span>Strict whitelist validation — zero arbitrary string eval</span>
            </div>
            <div className="flex items-center gap-2 text-xs font-mono text-[#4DD9C4]">
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span>Execution logged with before/after row metrics</span>
            </div>
          </div>
        </div>

        {/* Code Blocks */}
        <div className="space-y-3 font-mono text-xs">
          <div>
            <span className="text-[#8B92A3] text-[11px] block mb-1">Glasswork JSON DSL Spec:</span>
            <pre className="p-3 rounded bg-[#12161F] border border-white/10 text-[#4DD9C4] overflow-x-auto text-[11px]">
              {activeOp.sampleDsl}
            </pre>
          </div>

          <div>
            <span className="text-[#8B92A3] text-[11px] block mb-1">Pandas Execution Under the Hood:</span>
            <pre className="p-3 rounded bg-[#12161F] border border-white/10 text-[#F5A623] overflow-x-auto text-[11px]">
              {activeOp.pandasCode}
            </pre>
          </div>
        </div>
      </motion.div>
    </section>
  );
}
